class PopulateSysadmTestData < ApplicationRecord
  include ClassLogger
  Rails.application.config.after_initialize do
    if Settings.edodb.adapter == 'postgresql'
      logger.warn('Initializing mock SYSADM test data')
      establish_connection :edodb_test
      sql = <<-SQL

      DROP SCHEMA IF EXISTS SYSADM CASCADE;
      CREATE SCHEMA SYSADM;

      DROP TABLE IF EXISTS SYSADM.BOA_ADVISEE_NOTE00_VW;
      CREATE TABLE SYSADM.BOA_ADVISEE_NOTE00_VW (
        EMPLID	VARCHAR(11),
        SAA_NOTE_ID	VARCHAR(5),
        SAA_SEQ_NBR NUMERIC(38),
        SCI_NOTE_PRIORITY	VARCHAR(10),
        SAA_NOTE_ITM_LONG	TEXT,
        SCC_ROW_ADD_OPRID	VARCHAR(30),
        SCC_ROW_ADD_DTTM	TIMESTAMP(6),
        SCC_ROW_UPD_OPRID	VARCHAR(30),
        SCC_ROW_UPD_DTTM	TIMESTAMP(6),
        SCI_APPT_ID	VARCHAR(10),
        SAA_NOTE_TYPE	VARCHAR(10),
        SAA_NOTE_SUBTYPE	VARCHAR(10),
        ADVISOR_ID	VARCHAR(11),
        SCI_TOPIC	VARCHAR(30),
        UC_ADV_TYP_DESC	VARCHAR(30),
        UC_ADV_SUBTYP_DESC	VARCHAR(30)
      );
      INSERT INTO SYSADM.BOA_ADVISEE_NOTE00_VW (EMPLID,SAA_NOTE_ID,SAA_SEQ_NBR,SCI_NOTE_PRIORITY,SAA_NOTE_ITM_LONG,SCC_ROW_ADD_OPRID,SCC_ROW_ADD_DTTM,SCC_ROW_UPD_OPRID,SCC_ROW_UPD_DTTM,SCI_APPT_ID,SAA_NOTE_TYPE,SAA_NOTE_SUBTYPE,ADVISOR_ID,SCI_TOPIC,UC_ADV_TYP_DESC,UC_ADV_SUBTYP_DESC) VALUES ('11667051','00005',2,'High','<p>I am the note body</p>','1231231','2013-03-16 11:29:13.000000','4564564','2018-11-01 11:29:13.000000',' ','VADMIN','ENTRYNOCNT','3033514124','Academic Progress','Administrative','Entry w/o Contact');
      INSERT INTO SYSADM.BOA_ADVISEE_NOTE00_VW (EMPLID,SAA_NOTE_ID,SAA_SEQ_NBR,SCI_NOTE_PRIORITY,SAA_NOTE_ITM_LONG,SCC_ROW_ADD_OPRID,SCC_ROW_ADD_DTTM,SCC_ROW_UPD_OPRID,SCC_ROW_UPD_DTTM,SCI_APPT_ID,SAA_NOTE_TYPE,SAA_NOTE_SUBTYPE,ADVISOR_ID,SCI_TOPIC,UC_ADV_TYP_DESC,UC_ADV_SUBTYP_DESC) VALUES ('11667051','00005',2,'High','<p>I am the note body</p>','1231231','2013-03-16 11:29:13.000000','4564564','2018-11-01 11:29:13.000000',' ','VADMIN','ENTRYNOCNT','3033514124','APR','Administrative','Entry w/o Contact');
      INSERT INTO SYSADM.BOA_ADVISEE_NOTE00_VW (EMPLID,SAA_NOTE_ID,SAA_SEQ_NBR,SCI_NOTE_PRIORITY,SAA_NOTE_ITM_LONG,SCC_ROW_ADD_OPRID,SCC_ROW_ADD_DTTM,SCC_ROW_UPD_OPRID,SCC_ROW_UPD_DTTM,SCI_APPT_ID,SAA_NOTE_TYPE,SAA_NOTE_SUBTYPE,ADVISOR_ID,SCI_TOPIC,UC_ADV_TYP_DESC,UC_ADV_SUBTYP_DESC) VALUES ('11667051','00005',2,'High','<p>I am the note body</p>','1231231','2013-03-16 11:29:13.000000','4564564','2018-11-01 11:29:13.000000',' ','VADMIN','ENTRYNOCNT','3033514124','Degree Requirements','Administrative','Entry w/o Contact');

      DROP TABLE IF EXISTS SYSADM.BOA_ADVISE_USERATTACHFILENAME00_VW;
      CREATE TABLE SYSADM.BOA_ADVISE_USERATTACHFILENAME00_VW (
        EMPLID	VARCHAR(11),
        SAA_NOTE_ID	VARCHAR(5),
        SAA_SEQ_NBR NUMERIC(38),
        USERFILENAME	VARCHAR(64),
        ATTACHSYSFILENAME	VARCHAR(128)
      );
      INSERT INTO SYSADM.BOA_ADVISE_USERATTACHFILENAME00_VW (EMPLID,SAA_NOTE_ID,SAA_SEQ_NBR,USERFILENAME,ATTACHSYSFILENAME) VALUES ('11667051','00005',1,'1234_001.pdf','11667051_00005_1.pdf');
      INSERT INTO SYSADM.BOA_ADVISE_USERATTACHFILENAME00_VW (EMPLID,SAA_NOTE_ID,SAA_SEQ_NBR,USERFILENAME,ATTACHSYSFILENAME) VALUES ('11667051','00005',1,'5678_001.pdf','11667051_00005_2.pdf');

      DROP TABLE IF EXISTS SYSADM.BOA_STUDENT_ADVISOR_VW;
      CREATE TABLE SYSADM.BOA_STUDENT_ADVISOR_VW (
        STUDENT_ID	VARCHAR(11),
        CAMPUS_ID	VARCHAR(16),
        INSTITUTION	VARCHAR(5),
        ACADEMIC_CAREER	VARCHAR(4),
        ACADEMIC_PROGRAM	VARCHAR(5),
        ACADEMIC_PLAN	VARCHAR(10),
        ADVISOR_ROLE	VARCHAR(4),
        ADVISOR_ID	VARCHAR(11),
        ACADEMIC_CAREER_DESCR	VARCHAR(30),
        ACADEMIC_PROGRAM_DESCR	VARCHAR(30),
        ACADEMIC_PLAN_DESCR	VARCHAR(30),
        ADVISOR_ROLE_DESCR	VARCHAR(30)
      );
      INSERT INTO SYSADM.BOA_STUDENT_ADVISOR_VW (STUDENT_ID,CAMPUS_ID,INSTITUTION,ACADEMIC_CAREER,ACADEMIC_PROGRAM,ACADEMIC_PLAN,ADVISOR_ROLE,ADVISOR_ID,ACADEMIC_CAREER_DESCR,ACADEMIC_PROGRAM_DESCR,ACADEMIC_PLAN_DESCR,ADVISOR_ROLE_DESCR) VALUES ('11667051','61889','UCB01','UGRD','UCLS','252A9U','MAJ','303123456','Undergraduate','Undergrad Letters & Science','Media Studies BA','Major Advisor');
      INSERT INTO SYSADM.BOA_STUDENT_ADVISOR_VW (STUDENT_ID,CAMPUS_ID,INSTITUTION,ACADEMIC_CAREER,ACADEMIC_PROGRAM,ACADEMIC_PLAN,ADVISOR_ROLE,ADVISOR_ID,ACADEMIC_CAREER_DESCR,ACADEMIC_PROGRAM_DESCR,ACADEMIC_PLAN_DESCR,ADVISOR_ROLE_DESCR) VALUES ('11667051','61889','UCB01','UGRD','UCED','19084U','COLL','303234567','Undergraduate','Undergrad Environmental Design','Architecture BA','College Advisor');
      INSERT INTO SYSADM.BOA_STUDENT_ADVISOR_VW (STUDENT_ID,CAMPUS_ID,INSTITUTION,ACADEMIC_CAREER,ACADEMIC_PROGRAM,ACADEMIC_PLAN,ADVISOR_ROLE,ADVISOR_ID,ACADEMIC_CAREER_DESCR,ACADEMIC_PROGRAM_DESCR,ACADEMIC_PLAN_DESCR,ADVISOR_ROLE_DESCR) VALUES ('11667051','61889','UCB01','GRAD','GACAD','00360PHDG','GRAD','303345678','Graduate','Graduate Academic Programs','Ethnic Studies PhD','Grad Div Representative');

      DROP TABLE IF EXISTS SYSADM.BOA_INSTRUCTOR_ADVISOR_VW;
      CREATE TABLE SYSADM.BOA_INSTRUCTOR_ADVISOR_VW (
        ADVISOR_ID	VARCHAR(11),
        CAMPUS_ID	VARCHAR(16),
        INSTITUTION	VARCHAR(5),
        INSTRUCTOR_ADISOR_NUMBER NUMERIC(38),
        ADVISOR_TYPE	VARCHAR(4),
        EFFECTIVE_DATE	DATE,
        EFFECTIVE_STATUS	VARCHAR(1),
        ACADEMIC_ORGANIZATION	VARCHAR(10),
        ADVISOR_FLAG	VARCHAR(1),
        INSTRUCTOR_TYPE	VARCHAR(4),
        ACADEMIC_CAREER	VARCHAR(4),
        ACADEMIC_PROGRAM	VARCHAR(5),
        ACADEMIC_PLAN	VARCHAR(10),
        ACADEMIC_SUB_PLAN	VARCHAR(10),
        ACADEMIC_CAREER_DESCR	VARCHAR(30),
        ACADEMIC_PROGRAM_DESCR	VARCHAR(30),
        ACADEMIC_PLAN_DESCR	VARCHAR(30),
        ACADEMIC_SUB_PLAN_DESCR	VARCHAR(30),
        ADVISOR_TYPE_DESCR	VARCHAR(30),
        INSTRUCTOR_TYPE_DESCR	VARCHAR(30)
      );
      INSERT INTO SYSADM.BOA_INSTRUCTOR_ADVISOR_VW (ADVISOR_ID,CAMPUS_ID,INSTITUTION,INSTRUCTOR_ADISOR_NUMBER,ADVISOR_TYPE,EFFECTIVE_DATE,EFFECTIVE_STATUS,ACADEMIC_ORGANIZATION,ADVISOR_FLAG,INSTRUCTOR_TYPE,ACADEMIC_CAREER,ACADEMIC_PROGRAM,ACADEMIC_PLAN,ACADEMIC_SUB_PLAN,ACADEMIC_CAREER_DESCR,ACADEMIC_PROGRAM_DESCR,ACADEMIC_PLAN_DESCR,ACADEMIC_SUB_PLAN_DESCR,ADVISOR_TYPE_DESCR,INSTRUCTOR_TYPE_DESCR) VALUES ('303123456','123456','UCB01',1,'COLL','2018-07-31','A','UCB01','Y','ADV','UGRD','UCLS','25000U',' ','Undergraduate','Undergrad Letters & Science','Letters & Sci Undeclared UG',' ','College Advisor','Advisor Only');
      INSERT INTO SYSADM.BOA_INSTRUCTOR_ADVISOR_VW (ADVISOR_ID,CAMPUS_ID,INSTITUTION,INSTRUCTOR_ADISOR_NUMBER,ADVISOR_TYPE,EFFECTIVE_DATE,EFFECTIVE_STATUS,ACADEMIC_ORGANIZATION,ADVISOR_FLAG,INSTRUCTOR_TYPE,ACADEMIC_CAREER,ACADEMIC_PROGRAM,ACADEMIC_PLAN,ACADEMIC_SUB_PLAN,ACADEMIC_CAREER_DESCR,ACADEMIC_PROGRAM_DESCR,ACADEMIC_PLAN_DESCR,ACADEMIC_SUB_PLAN_DESCR,ADVISOR_TYPE_DESCR,INSTRUCTOR_TYPE_DESCR) VALUES ('303234567','234567','UCB01',1,'GEA','2016-07-01','A','UCB01','Y','INST','GRAD','GPRFL','19165CPCEG',' ','Graduate','Graduate Professional Programs','City & Reg Plan MCP-CEE MS CDP',' ','Graduate Equity Advisor','Instructor');
      INSERT INTO SYSADM.BOA_INSTRUCTOR_ADVISOR_VW (ADVISOR_ID,CAMPUS_ID,INSTITUTION,INSTRUCTOR_ADISOR_NUMBER,ADVISOR_TYPE,EFFECTIVE_DATE,EFFECTIVE_STATUS,ACADEMIC_ORGANIZATION,ADVISOR_FLAG,INSTRUCTOR_TYPE,ACADEMIC_CAREER,ACADEMIC_PROGRAM,ACADEMIC_PLAN,ACADEMIC_SUB_PLAN,ACADEMIC_CAREER_DESCR,ACADEMIC_PROGRAM_DESCR,ACADEMIC_PLAN_DESCR,ACADEMIC_SUB_PLAN_DESCR,ADVISOR_TYPE_DESCR,INSTRUCTOR_TYPE_DESCR) VALUES ('303234567','234567','UCB01',3,'GEA','2016-07-01','A','UCB01','Y','INST','GRAD','GPRFL','19165CPARG',' ','Graduate','Graduate Professional Programs','City & Reg Plan MCP-MArch CDP',' ','Graduate Equity Advisor','Instructor');

      DROP TABLE IF EXISTS SYSADM.BOA_ADV_NOTES_ACCESS_VW;
      CREATE TABLE SYSADM.BOA_ADV_NOTES_ACCESS_VW (
        USER_ID	VARCHAR(30),
        CS_ID	VARCHAR(11),
        PERMISSION_LIST	VARCHAR(30)
      );
      INSERT INTO SYSADM.BOA_ADV_NOTES_ACCESS_VW (USER_ID,CS_ID,PERMISSION_LIST) VALUES ('123456','303123456','UC_CS_AA_CURRICULAR_ADVISOR');
      INSERT INTO SYSADM.BOA_ADV_NOTES_ACCESS_VW (USER_ID,CS_ID,PERMISSION_LIST) VALUES ('234567','303234567','UC_CS_AA_CO_CURRICULAR_ADVISOR');
      INSERT INTO SYSADM.BOA_ADV_NOTES_ACCESS_VW (USER_ID,CS_ID,PERMISSION_LIST) VALUES ('345678','303345678','UC_CS_AA_ADVISOR_VIEW');
      
      SQL

      connection.execute sql
    end
  end
end
